# https://www.freecodecamp.org/news/publishing-github-event-data-with-github-actions-and-pages/
# https://stackoverflow.com/questions/58597010/how-to-access-a-github-issue-comment-body-using-github-actions
# This is a basic workflow to help you get started with Actions
# https://github.com/maguowei/iaas/blob/d48834c18b66ae0f3ae32e5e62a6811dfddadcb2/.github/workflows/iaas.yml

name: issue2post

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  issues:
    types: [opened, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Turn comment into file
        run: |
          cat <<'EOF' > _posts/"${{ github.event.issue.title }}".md
          ---
          layout: post
          title: ${{ github.event.issue.title }}
          date: ${{ github.event.issue.created_at }}
          ---
          ${{ github.event.issue.body }}
          EOF

      - name: Push changes to repo
        run: |
          REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git pull ${REMOTE}
          git checkout main
          git add .
          git status
          git commit -am "Add new comment"
          git push ${REMOTE} main
